# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_remove_picture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file_name',
            field=models.FileField(upload_to=b''),
        ),
    ]
