# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_auto_20170319_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file_name',
            field=models.FileField(blank=True, upload_to=b'owner.username'),
        ),
    ]
