# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:19
from __future__ import unicode_literals

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_auto_20170319_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file_name',
            field=private_storage.fields.PrivateFileField(blank=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=b'media'),
        ),
    ]
