# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:25
from __future__ import unicode_literals

from django.db import migrations
import file_storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0007_auto_20170319_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file_name',
            field=file_storage.models.CustomFileField(upload_to=b'dummy'),
        ),
    ]
